# Generated by Django 4.1.3 on 2022-12-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
    ]
